name: Host

on:
  release:
    types: [published, edited]

jobs:
  host:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install java
        run: sudo apt install openjdk-17-jre
      - name: Intall openvpn
        run: sudo apt install openvpn easy-rsa
      - name: Download openvpn configuration file
        run: curl ${{ secrets.OPENVPN_CONFIGURATION }} -o config.ovpn
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Run
        run: sudo dotnet run --project HostRunner/HostRunner.csproj --no-build --verbosity normal --configuration Release ${{ secrets.ACCESS_TOKEN }} ${{ secrets.REFRESH_TOKEN }} ${{ secrets.CLIENT_ID }} ${{ secrets.CLIENT_SECRET }} ${{ secrets.FOLDER_ID }} ${{ secrets.NGROK_TOKEN }}
