name: Host

on:
  release:
    types: [published, edited]

jobs:
  host:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      name: Run ngrok
      uses: apogiatzis/ngrok-tunneling-action@latest
      with:
        timeout: 6h
        port: 25565
        ngrok_authtoken: ${{ secrets.NGROK_TOKEN }}

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Run
        run: dotnet run --project HostRunner/HostRunner.csproj --no-build --verbosity normal --configuration Release ${{ secrets.ACCESS_TOKEN }} ${{ secrets.REFRESH_TOKEN }} ${{ secrets.CLIENT_ID }} ${{ secrets.CLIENT_SECRET }} ${{ secrets.FOLDER_ID }}
