name: Host

on:
  release:
    types: [published, edited]

jobs:
  host:
    runs-on: buildjet-4vcpu-ubuntu-2204

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Intall openvpn
        run: sudo apt install openvpn easy-rsa
      - name: Download openvpn configuration file
        run: curl ${{ secrets.OPENVPN_CONFIGURATION }} -o config.ovpn
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Run
        run: dotnet run --project HostRunner/HostRunner.csproj --no-build --verbosity normal --configuration Release ${{ secrets.ACCESS_TOKEN }} ${{ secrets.REFRESH_TOKEN }} ${{ secrets.CLIENT_ID }} ${{ secrets.CLIENT_SECRET }} ${{ secrets.FOLDER_ID }}
