name: Host

on:
  release:
    types: [published, edited]

jobs:
  host:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Intall openvpn
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt install openvpn easy-rsa
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install openvpn
          fi
        shell: bash
      - name: Download openvpn configuration file
        run: curl ${{ secrets.OPENVPN_CONFIGURATION }} -o config.ovpn
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Run
        run: dotnet run --project HostRunner/HostRunner.csproj --no-build --verbosity normal --configuration Release ${{ secrets.ACCESS_TOKEN }} ${{ secrets.REFRESH_TOKEN }} ${{ secrets.CLIENT_ID }} ${{ secrets.CLIENT_SECRET }} ${{ secrets.FOLDER_ID }}
      - name: Run new job
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ github.GITHUB_RUN_ID }}